// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pinkhaFFI)
import pinkhaFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pinkha_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pinkha_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePinkhaInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol PinkhaApiProtocol: AnyObject, Sendable {
    
    /**
     * Ajoute un bloc ; le contenu est passé en JSON (BlockContent sérialisé).
     * Retourne le document mis à jour en JSON.
     */
    func addBlock(docId: String, blockContentJson: String) throws  -> String
    
    /**
     * Ajoute un bloc enfant ; le contenu est passé en JSON (BlockContent sérialisé).
     */
    func addChildBlock(docId: String, parentId: String, blockContentJson: String) throws  -> String
    
    /**
     * Ajoute une entrée ; `values_json` est une map UUID -> ValeurPropriete sérialisée.
     */
    func addEntry(dbId: String, valuesJson: String) throws  -> String
    
    /**
     * Ajoute une propriété sérialisée en JSON.
     */
    func addProperty(dbId: String, propertyJson: String) throws 
    
    /**
     * Ajoute une vue sérialisée en JSON.
     */
    func addView(dbId: String, viewJson: String) throws  -> String
    
    /**
     * Retourne l'agrégat d'une colonne en JSON.
     */
    func columnAggregateDatabaseJson(dbId: String, propertyId: String, aggregateJson: String) throws  -> String
    
    /**
     * Crée une nouvelle database et retourne son UUID.
     */
    func createDatabase(title: String) throws  -> String
    
    /**
     * Crée un nouveau document et retourne son UUID.
     */
    func createDocument(title: String) throws  -> String
    
    func createFolder(name: String, parentId: String?) throws  -> FolderMetaFfi
    
    /**
     * Soft-deletes every database. Returns the number deleted.
     */
    func deleteAllDatabases() throws  -> UInt32
    
    /**
     * Soft-delete de tous les documents. Retourne le nombre supprimé.
     */
    func deleteAllDocuments() throws  -> UInt32
    
    func deleteBlock(docId: String, blockId: String) throws 
    
    /**
     * Soft-delete de la database.
     */
    func deleteDatabase(id: String) throws 
    
    /**
     * Soft-delete du document.
     */
    func deleteDocument(id: String) throws 
    
    func deleteEntry(dbId: String, entryId: String) throws 
    
    func deleteFolder(id: String) throws 
    
    func deleteProperty(dbId: String, propertyId: String) throws 
    
    func deleteView(dbId: String, viewId: String) throws 
    
    /**
     * Retourne la database complète sérialisée en JSON (avec entrées et vues).
     */
    func getDatabaseJson(id: String) throws  -> String
    
    /**
     * Retourne le document complet sérialisé en JSON (avec blocs).
     */
    func getDocumentJson(id: String) throws  -> String
    
    func getFolder(id: String) throws  -> FolderMetaFfi
    
    /**
     * Retourne les groupes d'entrées en JSON.
     */
    func groupedQueryDatabaseJson(dbId: String, viewId: String, groupBy: String) throws  -> String
    
    /**
     * Importe les notes Bear depuis la SQLite locale de Bear.
     * `db_path` est le chemin absolu vers `database.sqlite` de Bear.
     */
    func importFromBear(dbPath: String) async throws  -> ImportResultFfi
    
    /**
     * Importe les pages Craft depuis le fichier `.realm` local de Craft.
     * `db_path` est le chemin absolu vers le fichier `.realm` de Craft.
     */
    func importFromCraft(dbPath: String) async throws  -> ImportResultFfi
    
    /**
     * Combine le fichier `.realm` de Craft et un dossier de `.textbundle` :
     * les pages ayant un textbundle correspondant utilisent son contenu markdown ;
     * les autres pages utilisent le contenu realm.
     */
    func importFromCraftCombined(realmPath: String, textbundleRoot: String) async throws  -> ImportResultFfi
    
    /**
     * Importe les pages Craft depuis un dossier de `.textbundle` exporté par Craft.
     * `root_dir` est le chemin absolu vers le dossier racine de l'export.
     */
    func importFromCraftTextbundle(rootDir: String) async throws  -> ImportResultFfi
    
    /**
     * Importe une database Notion complète (schéma + pages + blocs).
     * `token` est un bearer token OAuth2 ou private integration token.
     * `database_id` est un UUID 32-char hex ou l'URL complète Notion.
     *
     * Synchrone côté FFI : Notion utilise `reqwest`, qui exige un runtime
     * Tokio absent de l'executor UniFFI. On `block_on` côté Rust, donc Swift
     * doit appeler depuis `Task.detached` pour ne pas bloquer le main thread.
     * `covers_dir` est un chemin absolu vers un dossier existant où les
     * images de cover sont téléchargées. Quand null, on stocke seulement
     * l'URL — OK pour les covers externes mais celles hébergées par Notion
     * expirent au bout d'~1h.
     */
    func importFromNotion(token: String, databaseId: String, coversDir: String?) throws  -> ImportResultFfi
    
    /**
     * Indente un bloc : le déplace sous le frère précédent au même niveau.
     * `InvalidOperation` si le bloc est le premier de son niveau.
     */
    func indentBlock(docId: String, blockId: String) throws 
    
    /**
     * Liste les métadonnées de toutes les databases actives.
     */
    func listDatabases() throws  -> [DatabaseMetaFfi]
    
    /**
     * Liste les databases en corbeille (soft-deleted), du plus récemment supprimé en premier.
     */
    func listDeletedDatabases() throws  -> [DatabaseMetaFfi]
    
    /**
     * Liste les documents en corbeille (soft-deleted), du plus récemment supprimé en premier.
     */
    func listDeletedDocuments() throws  -> [DocumentMetaFfi]
    
    /**
     * Liste les entries soft-deleted d'une database (JSON array).
     */
    func listDeletedEntriesJson(dbId: String) throws  -> String
    
    /**
     * Liste les dossiers en corbeille (soft-deleted), du plus récemment supprimé en premier.
     */
    func listDeletedFolders() throws  -> [FolderMetaFfi]
    
    /**
     * Liste les métadonnées de tous les documents actifs.
     */
    func listDocuments() throws  -> [DocumentMetaFfi]
    
    func listDocumentsInFolder(folderId: String?) throws  -> [DocumentMetaFfi]
    
    func listFolders() throws  -> [FolderMetaFfi]
    
    /**
     * Liste les databases Notion accessibles avec le token donné. Utilisé
     * par le picker côté Swift pour éviter à l'utilisateur de coller des URLs.
     */
    func listNotionDatabases(token: String) throws  -> [NotionDatabaseSummaryFfi]
    
    /**
     * Déplace un bloc vers un parent ou vers la racine si `new_parent_id` est nul.
     */
    func moveBlock(docId: String, blockId: String, newParentId: String?) throws 
    
    func moveDocumentToFolder(docId: String, folderId: String?) throws 
    
    func moveFolderTo(id: String, newParentId: String?) throws 
    
    /**
     * Désindente un bloc : le sort de son parent et le replace au niveau du
     * grand-parent, juste après l'ancien parent. `InvalidOperation` si le
     * bloc est déjà à la racine.
     */
    func outdentBlock(docId: String, blockId: String) throws 
    
    /**
     * Supprime définitivement une database de la corbeille (hard delete).
     */
    func purgeDatabase(id: String) throws 
    
    /**
     * Supprime définitivement un document de la corbeille (hard delete).
     */
    func purgeDocument(id: String) throws 
    
    /**
     * Supprime définitivement une entry soft-deleted (hard delete).
     */
    func purgeEntry(dbId: String, entryId: String) throws 
    
    /**
     * Supprime définitivement un dossier de la corbeille (hard delete).
     */
    func purgeFolder(id: String) throws 
    
    /**
     * Retourne les entrées filtrées/triées en JSON.
     */
    func queryDatabaseJson(dbId: String, viewId: String) throws  -> String
    
    /**
     * Retourne les entrées filtrées/triées avec rollups calculés en JSON.
     */
    func queryDatabaseWithRollupsJson(dbId: String, viewId: String) throws  -> String
    
    func renameFolder(id: String, newName: String) throws 
    
    func renameProperty(dbId: String, propertyId: String, newName: String) throws 
    
    /**
     * Réordonne les blocs racine selon la liste d'UUIDs fournie.
     */
    func reorderBlocks(docId: String, order: [String]) throws 
    
    /**
     * Réordonne les enfants directs d'un bloc parent.
     */
    func reorderChildBlocks(docId: String, parentId: String, order: [String]) throws 
    
    /**
     * Restaure une database depuis la corbeille.
     */
    func restoreDatabase(id: String) throws 
    
    /**
     * Restaure un document depuis la corbeille.
     */
    func restoreDocument(id: String) throws 
    
    /**
     * Restaure une entry depuis la corbeille de sa database.
     */
    func restoreEntry(dbId: String, entryId: String) throws 
    
    /**
     * Restaure un dossier depuis la corbeille.
     */
    func restoreFolder(id: String) throws 
    
    /**
     * Retourne les entrées correspondant à la recherche en JSON.
     */
    func searchDatabaseEntriesJson(dbId: String, query: String) throws  -> String
    
    /**
     * Recherche insensible à la casse dans les titles.
     */
    func searchDocuments(query: String) throws  -> [DocumentMetaFfi]
    
    /**
     * Recherche plein texte dans les blocs.
     */
    func searchInBlocks(query: String) throws  -> [DocumentMetaFfi]
    
    /**
     * Pose ou retire la couleur d'un bloc (texte). `color` est un nom de
     * couleur (`"red"`, `"blue"`, etc.) ou `null` pour revenir au thème.
     * Les couleurs inline sur les spans ont toujours priorité.
     */
    func setBlockColor(docId: String, blockId: String, color: String?) throws 
    
    /**
     * Pose un tri unique sur une vue, en remplaçant ceux qui existent.
     * `property_id = null` retire le tri.
     */
    func setViewSort(dbId: String, viewId: String, propertyId: String?, ascending: Bool) throws 
    
    /**
     * Remplace le contenu d'un bloc existant (JSON de BlockContent).
     */
    func updateBlock(docId: String, blockId: String, contentJson: String) throws 
    
    func updateDocumentCover(id: String, cover: String?) throws 
    
    /**
     * Pose ou retire l'icône d'un document (emoji, filename local, ou URL).
     */
    func updateDocumentIcon(id: String, icon: String?) throws 
    
    func updateDocumentTitle(id: String, newTitle: String) throws 
    
    func updateEntry(dbId: String, entryId: String, valuesJson: String) throws 
    
    func updateView(dbId: String, viewId: String, filtersJson: String, sortsJson: String) throws 
    
}
open class PinkhaApi: PinkhaApiProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_pinkha_fn_clone_pinkhaapi(self.handle, $0) }
    }
    /**
     * Ouvre (ou crée) la base SQLite au chemin donné.
     */
public convenience init(dbPath: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_constructor_pinkhaapi_new(
        FfiConverterString.lower(dbPath),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_pinkha_fn_free_pinkhaapi(handle, $0) }
    }

    

    
    /**
     * Ajoute un bloc ; le contenu est passé en JSON (BlockContent sérialisé).
     * Retourne le document mis à jour en JSON.
     */
open func addBlock(docId: String, blockContentJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_add_block(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(blockContentJson),$0
    )
})
}
    
    /**
     * Ajoute un bloc enfant ; le contenu est passé en JSON (BlockContent sérialisé).
     */
open func addChildBlock(docId: String, parentId: String, blockContentJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_add_child_block(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(parentId),
        FfiConverterString.lower(blockContentJson),$0
    )
})
}
    
    /**
     * Ajoute une entrée ; `values_json` est une map UUID -> ValeurPropriete sérialisée.
     */
open func addEntry(dbId: String, valuesJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_add_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(valuesJson),$0
    )
})
}
    
    /**
     * Ajoute une propriété sérialisée en JSON.
     */
open func addProperty(dbId: String, propertyJson: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_add_property(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(propertyJson),$0
    )
}
}
    
    /**
     * Ajoute une vue sérialisée en JSON.
     */
open func addView(dbId: String, viewJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_add_view(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(viewJson),$0
    )
})
}
    
    /**
     * Retourne l'agrégat d'une colonne en JSON.
     */
open func columnAggregateDatabaseJson(dbId: String, propertyId: String, aggregateJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_column_aggregate_database_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(propertyId),
        FfiConverterString.lower(aggregateJson),$0
    )
})
}
    
    /**
     * Crée une nouvelle database et retourne son UUID.
     */
open func createDatabase(title: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_create_database(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(title),$0
    )
})
}
    
    /**
     * Crée un nouveau document et retourne son UUID.
     */
open func createDocument(title: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_create_document(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(title),$0
    )
})
}
    
open func createFolder(name: String, parentId: String?)throws  -> FolderMetaFfi  {
    return try  FfiConverterTypeFolderMetaFfi_lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_create_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterOptionString.lower(parentId),$0
    )
})
}
    
    /**
     * Soft-deletes every database. Returns the number deleted.
     */
open func deleteAllDatabases()throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_all_databases(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Soft-delete de tous les documents. Retourne le nombre supprimé.
     */
open func deleteAllDocuments()throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_all_documents(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func deleteBlock(docId: String, blockId: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_block(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(blockId),$0
    )
}
}
    
    /**
     * Soft-delete de la database.
     */
open func deleteDatabase(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_database(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Soft-delete du document.
     */
open func deleteDocument(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_document(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func deleteEntry(dbId: String, entryId: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(entryId),$0
    )
}
}
    
open func deleteFolder(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func deleteProperty(dbId: String, propertyId: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_property(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(propertyId),$0
    )
}
}
    
open func deleteView(dbId: String, viewId: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_delete_view(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(viewId),$0
    )
}
}
    
    /**
     * Retourne la database complète sérialisée en JSON (avec entrées et vues).
     */
open func getDatabaseJson(id: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_get_database_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Retourne le document complet sérialisé en JSON (avec blocs).
     */
open func getDocumentJson(id: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_get_document_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func getFolder(id: String)throws  -> FolderMetaFfi  {
    return try  FfiConverterTypeFolderMetaFfi_lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_get_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Retourne les groupes d'entrées en JSON.
     */
open func groupedQueryDatabaseJson(dbId: String, viewId: String, groupBy: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_grouped_query_database_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(viewId),
        FfiConverterString.lower(groupBy),$0
    )
})
}
    
    /**
     * Importe les notes Bear depuis la SQLite locale de Bear.
     * `db_path` est le chemin absolu vers `database.sqlite` de Bear.
     */
open func importFromBear(dbPath: String)async throws  -> ImportResultFfi  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pinkha_fn_method_pinkhaapi_import_from_bear(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(dbPath)
                )
            },
            pollFunc: ffi_pinkha_rust_future_poll_rust_buffer,
            completeFunc: ffi_pinkha_rust_future_complete_rust_buffer,
            freeFunc: ffi_pinkha_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeImportResultFfi_lift,
            errorHandler: FfiConverterTypePinkhaError_lift
        )
}
    
    /**
     * Importe les pages Craft depuis le fichier `.realm` local de Craft.
     * `db_path` est le chemin absolu vers le fichier `.realm` de Craft.
     */
open func importFromCraft(dbPath: String)async throws  -> ImportResultFfi  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pinkha_fn_method_pinkhaapi_import_from_craft(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(dbPath)
                )
            },
            pollFunc: ffi_pinkha_rust_future_poll_rust_buffer,
            completeFunc: ffi_pinkha_rust_future_complete_rust_buffer,
            freeFunc: ffi_pinkha_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeImportResultFfi_lift,
            errorHandler: FfiConverterTypePinkhaError_lift
        )
}
    
    /**
     * Combine le fichier `.realm` de Craft et un dossier de `.textbundle` :
     * les pages ayant un textbundle correspondant utilisent son contenu markdown ;
     * les autres pages utilisent le contenu realm.
     */
open func importFromCraftCombined(realmPath: String, textbundleRoot: String)async throws  -> ImportResultFfi  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pinkha_fn_method_pinkhaapi_import_from_craft_combined(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(realmPath),FfiConverterString.lower(textbundleRoot)
                )
            },
            pollFunc: ffi_pinkha_rust_future_poll_rust_buffer,
            completeFunc: ffi_pinkha_rust_future_complete_rust_buffer,
            freeFunc: ffi_pinkha_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeImportResultFfi_lift,
            errorHandler: FfiConverterTypePinkhaError_lift
        )
}
    
    /**
     * Importe les pages Craft depuis un dossier de `.textbundle` exporté par Craft.
     * `root_dir` est le chemin absolu vers le dossier racine de l'export.
     */
open func importFromCraftTextbundle(rootDir: String)async throws  -> ImportResultFfi  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pinkha_fn_method_pinkhaapi_import_from_craft_textbundle(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(rootDir)
                )
            },
            pollFunc: ffi_pinkha_rust_future_poll_rust_buffer,
            completeFunc: ffi_pinkha_rust_future_complete_rust_buffer,
            freeFunc: ffi_pinkha_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeImportResultFfi_lift,
            errorHandler: FfiConverterTypePinkhaError_lift
        )
}
    
    /**
     * Importe une database Notion complète (schéma + pages + blocs).
     * `token` est un bearer token OAuth2 ou private integration token.
     * `database_id` est un UUID 32-char hex ou l'URL complète Notion.
     *
     * Synchrone côté FFI : Notion utilise `reqwest`, qui exige un runtime
     * Tokio absent de l'executor UniFFI. On `block_on` côté Rust, donc Swift
     * doit appeler depuis `Task.detached` pour ne pas bloquer le main thread.
     * `covers_dir` est un chemin absolu vers un dossier existant où les
     * images de cover sont téléchargées. Quand null, on stocke seulement
     * l'URL — OK pour les covers externes mais celles hébergées par Notion
     * expirent au bout d'~1h.
     */
open func importFromNotion(token: String, databaseId: String, coversDir: String?)throws  -> ImportResultFfi  {
    return try  FfiConverterTypeImportResultFfi_lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_import_from_notion(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(token),
        FfiConverterString.lower(databaseId),
        FfiConverterOptionString.lower(coversDir),$0
    )
})
}
    
    /**
     * Indente un bloc : le déplace sous le frère précédent au même niveau.
     * `InvalidOperation` si le bloc est le premier de son niveau.
     */
open func indentBlock(docId: String, blockId: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_indent_block(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(blockId),$0
    )
}
}
    
    /**
     * Liste les métadonnées de toutes les databases actives.
     */
open func listDatabases()throws  -> [DatabaseMetaFfi]  {
    return try  FfiConverterSequenceTypeDatabaseMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_databases(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Liste les databases en corbeille (soft-deleted), du plus récemment supprimé en premier.
     */
open func listDeletedDatabases()throws  -> [DatabaseMetaFfi]  {
    return try  FfiConverterSequenceTypeDatabaseMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_deleted_databases(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Liste les documents en corbeille (soft-deleted), du plus récemment supprimé en premier.
     */
open func listDeletedDocuments()throws  -> [DocumentMetaFfi]  {
    return try  FfiConverterSequenceTypeDocumentMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_deleted_documents(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Liste les entries soft-deleted d'une database (JSON array).
     */
open func listDeletedEntriesJson(dbId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_deleted_entries_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),$0
    )
})
}
    
    /**
     * Liste les dossiers en corbeille (soft-deleted), du plus récemment supprimé en premier.
     */
open func listDeletedFolders()throws  -> [FolderMetaFfi]  {
    return try  FfiConverterSequenceTypeFolderMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_deleted_folders(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Liste les métadonnées de tous les documents actifs.
     */
open func listDocuments()throws  -> [DocumentMetaFfi]  {
    return try  FfiConverterSequenceTypeDocumentMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_documents(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func listDocumentsInFolder(folderId: String?)throws  -> [DocumentMetaFfi]  {
    return try  FfiConverterSequenceTypeDocumentMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_documents_in_folder(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(folderId),$0
    )
})
}
    
open func listFolders()throws  -> [FolderMetaFfi]  {
    return try  FfiConverterSequenceTypeFolderMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_folders(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Liste les databases Notion accessibles avec le token donné. Utilisé
     * par le picker côté Swift pour éviter à l'utilisateur de coller des URLs.
     */
open func listNotionDatabases(token: String)throws  -> [NotionDatabaseSummaryFfi]  {
    return try  FfiConverterSequenceTypeNotionDatabaseSummaryFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_list_notion_databases(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(token),$0
    )
})
}
    
    /**
     * Déplace un bloc vers un parent ou vers la racine si `new_parent_id` est nul.
     */
open func moveBlock(docId: String, blockId: String, newParentId: String?)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_move_block(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(blockId),
        FfiConverterOptionString.lower(newParentId),$0
    )
}
}
    
open func moveDocumentToFolder(docId: String, folderId: String?)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_move_document_to_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterOptionString.lower(folderId),$0
    )
}
}
    
open func moveFolderTo(id: String, newParentId: String?)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_move_folder_to(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(newParentId),$0
    )
}
}
    
    /**
     * Désindente un bloc : le sort de son parent et le replace au niveau du
     * grand-parent, juste après l'ancien parent. `InvalidOperation` si le
     * bloc est déjà à la racine.
     */
open func outdentBlock(docId: String, blockId: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_outdent_block(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(blockId),$0
    )
}
}
    
    /**
     * Supprime définitivement une database de la corbeille (hard delete).
     */
open func purgeDatabase(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_purge_database(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Supprime définitivement un document de la corbeille (hard delete).
     */
open func purgeDocument(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_purge_document(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Supprime définitivement une entry soft-deleted (hard delete).
     */
open func purgeEntry(dbId: String, entryId: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_purge_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(entryId),$0
    )
}
}
    
    /**
     * Supprime définitivement un dossier de la corbeille (hard delete).
     */
open func purgeFolder(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_purge_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Retourne les entrées filtrées/triées en JSON.
     */
open func queryDatabaseJson(dbId: String, viewId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_query_database_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(viewId),$0
    )
})
}
    
    /**
     * Retourne les entrées filtrées/triées avec rollups calculés en JSON.
     */
open func queryDatabaseWithRollupsJson(dbId: String, viewId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_query_database_with_rollups_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(viewId),$0
    )
})
}
    
open func renameFolder(id: String, newName: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_rename_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(newName),$0
    )
}
}
    
open func renameProperty(dbId: String, propertyId: String, newName: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_rename_property(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(propertyId),
        FfiConverterString.lower(newName),$0
    )
}
}
    
    /**
     * Réordonne les blocs racine selon la liste d'UUIDs fournie.
     */
open func reorderBlocks(docId: String, order: [String])throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_reorder_blocks(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterSequenceString.lower(order),$0
    )
}
}
    
    /**
     * Réordonne les enfants directs d'un bloc parent.
     */
open func reorderChildBlocks(docId: String, parentId: String, order: [String])throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_reorder_child_blocks(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(parentId),
        FfiConverterSequenceString.lower(order),$0
    )
}
}
    
    /**
     * Restaure une database depuis la corbeille.
     */
open func restoreDatabase(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_restore_database(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Restaure un document depuis la corbeille.
     */
open func restoreDocument(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_restore_document(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Restaure une entry depuis la corbeille de sa database.
     */
open func restoreEntry(dbId: String, entryId: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_restore_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(entryId),$0
    )
}
}
    
    /**
     * Restaure un dossier depuis la corbeille.
     */
open func restoreFolder(id: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_restore_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Retourne les entrées correspondant à la recherche en JSON.
     */
open func searchDatabaseEntriesJson(dbId: String, query: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_search_database_entries_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Recherche insensible à la casse dans les titles.
     */
open func searchDocuments(query: String)throws  -> [DocumentMetaFfi]  {
    return try  FfiConverterSequenceTypeDocumentMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_search_documents(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Recherche plein texte dans les blocs.
     */
open func searchInBlocks(query: String)throws  -> [DocumentMetaFfi]  {
    return try  FfiConverterSequenceTypeDocumentMetaFfi.lift(try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_search_in_blocks(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Pose ou retire la couleur d'un bloc (texte). `color` est un nom de
     * couleur (`"red"`, `"blue"`, etc.) ou `null` pour revenir au thème.
     * Les couleurs inline sur les spans ont toujours priorité.
     */
open func setBlockColor(docId: String, blockId: String, color: String?)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_set_block_color(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(blockId),
        FfiConverterOptionString.lower(color),$0
    )
}
}
    
    /**
     * Pose un tri unique sur une vue, en remplaçant ceux qui existent.
     * `property_id = null` retire le tri.
     */
open func setViewSort(dbId: String, viewId: String, propertyId: String?, ascending: Bool)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_set_view_sort(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(viewId),
        FfiConverterOptionString.lower(propertyId),
        FfiConverterBool.lower(ascending),$0
    )
}
}
    
    /**
     * Remplace le contenu d'un bloc existant (JSON de BlockContent).
     */
open func updateBlock(docId: String, blockId: String, contentJson: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_update_block(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterString.lower(blockId),
        FfiConverterString.lower(contentJson),$0
    )
}
}
    
open func updateDocumentCover(id: String, cover: String?)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_update_document_cover(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(cover),$0
    )
}
}
    
    /**
     * Pose ou retire l'icône d'un document (emoji, filename local, ou URL).
     */
open func updateDocumentIcon(id: String, icon: String?)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_update_document_icon(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(icon),$0
    )
}
}
    
open func updateDocumentTitle(id: String, newTitle: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_update_document_title(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(newTitle),$0
    )
}
}
    
open func updateEntry(dbId: String, entryId: String, valuesJson: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_update_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(entryId),
        FfiConverterString.lower(valuesJson),$0
    )
}
}
    
open func updateView(dbId: String, viewId: String, filtersJson: String, sortsJson: String)throws   {try rustCallWithError(FfiConverterTypePinkhaError_lift) {
    uniffi_pinkha_fn_method_pinkhaapi_update_view(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbId),
        FfiConverterString.lower(viewId),
        FfiConverterString.lower(filtersJson),
        FfiConverterString.lower(sortsJson),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePinkhaApi: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PinkhaApi

    public static func lift(_ handle: UInt64) throws -> PinkhaApi {
        return PinkhaApi(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PinkhaApi) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PinkhaApi {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PinkhaApi, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinkhaApi_lift(_ handle: UInt64) throws -> PinkhaApi {
    return try FfiConverterTypePinkhaApi.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinkhaApi_lower(_ value: PinkhaApi) -> UInt64 {
    return FfiConverterTypePinkhaApi.lower(value)
}




/**
 * Métadonnées légères d'une database (sans entrées).
 */
public struct DatabaseMetaFfi: Equatable, Hashable {
    public var id: String
    public var titlePlain: String
    public var titleJson: String
    public var updatedAt: String
    public var createdAt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, titlePlain: String, titleJson: String, updatedAt: String, createdAt: String) {
        self.id = id
        self.titlePlain = titlePlain
        self.titleJson = titleJson
        self.updatedAt = updatedAt
        self.createdAt = createdAt
    }

    

    
}

#if compiler(>=6)
extension DatabaseMetaFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDatabaseMetaFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DatabaseMetaFfi {
        return
            try DatabaseMetaFfi(
                id: FfiConverterString.read(from: &buf), 
                titlePlain: FfiConverterString.read(from: &buf), 
                titleJson: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DatabaseMetaFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.titlePlain, into: &buf)
        FfiConverterString.write(value.titleJson, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatabaseMetaFfi_lift(_ buf: RustBuffer) throws -> DatabaseMetaFfi {
    return try FfiConverterTypeDatabaseMetaFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatabaseMetaFfi_lower(_ value: DatabaseMetaFfi) -> RustBuffer {
    return FfiConverterTypeDatabaseMetaFfi.lower(value)
}


/**
 * Métadonnées légères d'un document (sans blocs).
 */
public struct DocumentMetaFfi: Equatable, Hashable {
    public var id: String
    public var titlePlain: String
    public var titleJson: String
    public var cover: String?
    public var updatedAt: String
    public var createdAt: String
    public var folderId: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, titlePlain: String, titleJson: String, cover: String?, updatedAt: String, createdAt: String, folderId: String?) {
        self.id = id
        self.titlePlain = titlePlain
        self.titleJson = titleJson
        self.cover = cover
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.folderId = folderId
    }

    

    
}

#if compiler(>=6)
extension DocumentMetaFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocumentMetaFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocumentMetaFfi {
        return
            try DocumentMetaFfi(
                id: FfiConverterString.read(from: &buf), 
                titlePlain: FfiConverterString.read(from: &buf), 
                titleJson: FfiConverterString.read(from: &buf), 
                cover: FfiConverterOptionString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                folderId: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: DocumentMetaFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.titlePlain, into: &buf)
        FfiConverterString.write(value.titleJson, into: &buf)
        FfiConverterOptionString.write(value.cover, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterOptionString.write(value.folderId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocumentMetaFfi_lift(_ buf: RustBuffer) throws -> DocumentMetaFfi {
    return try FfiConverterTypeDocumentMetaFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocumentMetaFfi_lower(_ value: DocumentMetaFfi) -> RustBuffer {
    return FfiConverterTypeDocumentMetaFfi.lower(value)
}


/**
 * Métadonnées légères d'un dossier.
 */
public struct FolderMetaFfi: Equatable, Hashable {
    public var id: String
    public var name: String
    public var parentId: String?
    public var createdAt: String
    public var updatedAt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, parentId: String?, createdAt: String, updatedAt: String) {
        self.id = id
        self.name = name
        self.parentId = parentId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    

    
}

#if compiler(>=6)
extension FolderMetaFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFolderMetaFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FolderMetaFfi {
        return
            try FolderMetaFfi(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                parentId: FfiConverterOptionString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FolderMetaFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.parentId, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFolderMetaFfi_lift(_ buf: RustBuffer) throws -> FolderMetaFfi {
    return try FfiConverterTypeFolderMetaFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFolderMetaFfi_lower(_ value: FolderMetaFfi) -> RustBuffer {
    return FfiConverterTypeFolderMetaFfi.lower(value)
}


/**
 * Résumé d'une opération d'import retourné à Swift.
 */
public struct ImportResultFfi: Equatable, Hashable {
    public var app: String
    public var databaseId: String
    public var documents: UInt32
    public var entries: UInt32
    public var blocks: UInt32
    public var skipped: UInt32
    /**
     * Combined importer only: pages imported via textbundle content (0 otherwise).
     */
    public var matchedTextbundle: UInt32
    /**
     * Combined importer only: realm pages with no matching textbundle (0 otherwise).
     */
    public var realmFallback: UInt32
    /**
     * Combined importer only: textbundles with no matching realm page (0 otherwise).
     */
    public var textbundleOnly: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(app: String, databaseId: String, documents: UInt32, entries: UInt32, blocks: UInt32, skipped: UInt32, 
        /**
         * Combined importer only: pages imported via textbundle content (0 otherwise).
         */matchedTextbundle: UInt32, 
        /**
         * Combined importer only: realm pages with no matching textbundle (0 otherwise).
         */realmFallback: UInt32, 
        /**
         * Combined importer only: textbundles with no matching realm page (0 otherwise).
         */textbundleOnly: UInt32) {
        self.app = app
        self.databaseId = databaseId
        self.documents = documents
        self.entries = entries
        self.blocks = blocks
        self.skipped = skipped
        self.matchedTextbundle = matchedTextbundle
        self.realmFallback = realmFallback
        self.textbundleOnly = textbundleOnly
    }

    

    
}

#if compiler(>=6)
extension ImportResultFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImportResultFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImportResultFfi {
        return
            try ImportResultFfi(
                app: FfiConverterString.read(from: &buf), 
                databaseId: FfiConverterString.read(from: &buf), 
                documents: FfiConverterUInt32.read(from: &buf), 
                entries: FfiConverterUInt32.read(from: &buf), 
                blocks: FfiConverterUInt32.read(from: &buf), 
                skipped: FfiConverterUInt32.read(from: &buf), 
                matchedTextbundle: FfiConverterUInt32.read(from: &buf), 
                realmFallback: FfiConverterUInt32.read(from: &buf), 
                textbundleOnly: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ImportResultFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.app, into: &buf)
        FfiConverterString.write(value.databaseId, into: &buf)
        FfiConverterUInt32.write(value.documents, into: &buf)
        FfiConverterUInt32.write(value.entries, into: &buf)
        FfiConverterUInt32.write(value.blocks, into: &buf)
        FfiConverterUInt32.write(value.skipped, into: &buf)
        FfiConverterUInt32.write(value.matchedTextbundle, into: &buf)
        FfiConverterUInt32.write(value.realmFallback, into: &buf)
        FfiConverterUInt32.write(value.textbundleOnly, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImportResultFfi_lift(_ buf: RustBuffer) throws -> ImportResultFfi {
    return try FfiConverterTypeImportResultFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImportResultFfi_lower(_ value: ImportResultFfi) -> RustBuffer {
    return FfiConverterTypeImportResultFfi.lower(value)
}


/**
 * Résumé d'une database Notion retournée par `list_notion_databases` pour
 * le picker UI.
 */
public struct NotionDatabaseSummaryFfi: Equatable, Hashable {
    public var id: String
    public var title: String
    public var iconEmoji: String?
    public var lastEdited: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, title: String, iconEmoji: String?, lastEdited: String) {
        self.id = id
        self.title = title
        self.iconEmoji = iconEmoji
        self.lastEdited = lastEdited
    }

    

    
}

#if compiler(>=6)
extension NotionDatabaseSummaryFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNotionDatabaseSummaryFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NotionDatabaseSummaryFfi {
        return
            try NotionDatabaseSummaryFfi(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                iconEmoji: FfiConverterOptionString.read(from: &buf), 
                lastEdited: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: NotionDatabaseSummaryFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.iconEmoji, into: &buf)
        FfiConverterString.write(value.lastEdited, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNotionDatabaseSummaryFfi_lift(_ buf: RustBuffer) throws -> NotionDatabaseSummaryFfi {
    return try FfiConverterTypeNotionDatabaseSummaryFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNotionDatabaseSummaryFfi_lower(_ value: NotionDatabaseSummaryFfi) -> RustBuffer {
    return FfiConverterTypeNotionDatabaseSummaryFfi.lower(value)
}


public enum PinkhaError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case NotFound(id: String
    )
    case InvalidOperation(detail: String
    )
    case Storage(detail: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension PinkhaError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePinkhaError: FfiConverterRustBuffer {
    typealias SwiftType = PinkhaError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PinkhaError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotFound(
            id: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidOperation(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Storage(
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PinkhaError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .NotFound(id):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .InvalidOperation(detail):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Storage(detail):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinkhaError_lift(_ buf: RustBuffer) throws -> PinkhaError {
    return try FfiConverterTypePinkhaError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinkhaError_lower(_ value: PinkhaError) -> RustBuffer {
    return FfiConverterTypePinkhaError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDatabaseMetaFfi: FfiConverterRustBuffer {
    typealias SwiftType = [DatabaseMetaFfi]

    public static func write(_ value: [DatabaseMetaFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDatabaseMetaFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DatabaseMetaFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [DatabaseMetaFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDatabaseMetaFfi.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDocumentMetaFfi: FfiConverterRustBuffer {
    typealias SwiftType = [DocumentMetaFfi]

    public static func write(_ value: [DocumentMetaFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDocumentMetaFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DocumentMetaFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [DocumentMetaFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDocumentMetaFfi.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFolderMetaFfi: FfiConverterRustBuffer {
    typealias SwiftType = [FolderMetaFfi]

    public static func write(_ value: [FolderMetaFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFolderMetaFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FolderMetaFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [FolderMetaFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFolderMetaFfi.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeNotionDatabaseSummaryFfi: FfiConverterRustBuffer {
    typealias SwiftType = [NotionDatabaseSummaryFfi]

    public static func write(_ value: [NotionDatabaseSummaryFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeNotionDatabaseSummaryFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [NotionDatabaseSummaryFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [NotionDatabaseSummaryFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeNotionDatabaseSummaryFfi.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsurePinkhaInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pinkha_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_add_block() != 50968) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_add_child_block() != 20377) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_add_entry() != 43529) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_add_property() != 52071) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_add_view() != 30183) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_column_aggregate_database_json() != 24533) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_create_database() != 62218) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_create_document() != 6653) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_create_folder() != 49423) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_all_databases() != 61257) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_all_documents() != 3995) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_block() != 14109) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_database() != 12776) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_document() != 39039) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_entry() != 44863) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_folder() != 31554) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_property() != 45324) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_delete_view() != 42172) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_get_database_json() != 53195) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_get_document_json() != 23306) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_get_folder() != 38177) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_grouped_query_database_json() != 2473) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_import_from_bear() != 65442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_import_from_craft() != 6467) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_import_from_craft_combined() != 48693) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_import_from_craft_textbundle() != 42783) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_import_from_notion() != 18771) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_indent_block() != 34803) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_databases() != 58802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_deleted_databases() != 23880) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_deleted_documents() != 36222) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_deleted_entries_json() != 45731) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_deleted_folders() != 33419) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_documents() != 62408) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_documents_in_folder() != 8688) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_folders() != 40736) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_list_notion_databases() != 31016) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_move_block() != 56333) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_move_document_to_folder() != 22257) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_move_folder_to() != 28416) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_outdent_block() != 55400) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_purge_database() != 13513) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_purge_document() != 62109) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_purge_entry() != 63480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_purge_folder() != 8367) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_query_database_json() != 4012) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_query_database_with_rollups_json() != 38250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_rename_folder() != 49667) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_rename_property() != 36506) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_reorder_blocks() != 14489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_reorder_child_blocks() != 60852) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_restore_database() != 9191) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_restore_document() != 33151) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_restore_entry() != 19357) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_restore_folder() != 11915) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_search_database_entries_json() != 53101) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_search_documents() != 4353) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_search_in_blocks() != 65038) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_set_block_color() != 56489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_set_view_sort() != 45579) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_update_block() != 49420) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_update_document_cover() != 31520) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_update_document_icon() != 32890) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_update_document_title() != 35631) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_update_entry() != 34034) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_method_pinkhaapi_update_view() != 6165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pinkha_checksum_constructor_pinkhaapi_new() != 22429) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePinkhaInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all